### ISSUE TITLE
Can I set the disk size?

### ISSUE THREAD

**Issue by chrisdoman** [jbremer/vmcloak#116]
Im using the option to set the ram size but can't see an option to set the disk size.
The issue is when running a large number of cuckoo machines in parallel, some (likely when running ransomware) fill up the whole disk and cuckoo crashes out

**Comment by razuz** [comment]
isn't this related to cuckoo storage not vm disk ? Or probably you shouldn't fill up that much of files in vm ...

**Comment by chrisdoman** [comment]
Hehe well I could politely ask the malware to not encrypt all the files on the disk and write large junk files :)

The issue is the VMs are growing in size. I can fix this with a hack, just might be worth something to consider in vmcloak itself

**Comment by razuz** [comment]
yeah well sure :) 
let me see if I can make this option available for you in couple days as this feature could be used for other cases aswell

**Comment by razuz** [comment]
@chrisdoman I'm guessing PR #117 is what you're looking for ... 
new key --hddsize during vm init

**Comment by chrisdoman** [comment]
Sweet - thanks :D

**Comment by jbremer** [comment]
The PR mentioned above has now been merged (sorry for the delay).

**Comment by pdodia** [comment]
> @chrisdoman I'm guessing PR #117 is what you're looking for ...
> new key --hddsize during vm init

Is the default unit MB/ GB for the hard disk key in this command?
