### ISSUE TITLE
Firefox Dependency

### ISSUE THREAD

**Issue by fesleywox** [jbremer/vmcloak#134]
vmcloak install seven0 "firefox_41" returns "ERROR:vmcloak.abstract:could not find the correct installer!"
"firefox" also returns the same error

No issues with adobe9, dotnet, wic, chrome, ie10 

Ubuntu 16.04.5
Virtualbox - win7 Pro x86
vmcloak 0.4.5

**Comment by samwakel** [comment]
My workaround for this problem was to install firefox:41.0.2. The issue here is that VMCloak does not have a default version specified for Firefox so without specifying 41.0.2 it doesn't know what to install.

**Comment by fesleywox** [comment]
Thanks
