### ISSUE TITLE
Correct commands for new dependencies

### ISSUE THREAD

**Issue by fesleywox** [jbremer/vmcloak#135]
Hi .. having exhausted the google search for guidelines on commands to install different dependencies on vmcloak, I'm at a loss ?? 

I understand - vmcloak install chrome etc but for example dotnet ? If I want to install 4.5.2 how do I go about that?

I would love if somebody put a list together of the correct way to add dependencies and what OS they apply to eg x64 or x86, win XP Vista 7 10

**Comment by samwakel** [comment]
The usage for dependencies is (Name):(Version). For example firefox:41.0.2 pillow:3.4.2 winrar:5.40.

As for which ones work, the KB installers only work for Windows 7, XP has the least amount of working dependencies. IE11 seems to only work on Windows 7 etc.

The best way to find out is run vmcloak install (VM) (dependency1) (dependency2) etc with a list of everything you want and it'll throw an error when it hits one it can't do, then just remove that one from the list.

For some dependencies, like office, you have to give it some parameters. You can do that by running vmcloak install (VM) office office.isopath=path/to/ISO.iso office.serialkey=xxxx-xxxx-xxxx-xxxx office.activate=1 etc.

Hope this helps :)

**Comment by fesleywox** [comment]
> The usage for dependencies is (Name):(Version). For example firefox:41.0.2 pillow:3.4.2 winrar:5.40.
> 
> As for which ones work, the KB installers only work for Windows 7, XP has the least amount of working dependencies. IE11 seems to only work on Windows 7 etc.
> 
> The best way to find out is run vmcloak install (VM) (dependency1) (dependency2) etc with a list of everything you want and it'll throw an error when it hits one it can't do, then just remove that one from the list.
> 
> For some dependencies, like office, you have to give it some parameters. You can do that by running vmcloak install (VM) office office.isopath=path/to/ISO.iso office.serialkey=xxxx-xxxx-xxxx-xxxx office.activate=1 etc.
> 
> Hope this helps :)

Yep .. It make perfect sense.
Thanks for that.
