### ISSUE TITLE
Create ISO Fails

### ISSUE THREAD

**Issue by dsplice** [jbremer/vmcloak#27]
When creating the iso, vmcloak fails due to a missing directory (eg /tmp/tmpPgkZbZ/i386 (the i386 directory is not created therefor line 116 of misc.py fails). When created manually, the command succeeds.

**Comment by jbremer** [comment]
Are you sure your ``/mnt/winxp`` has a ``i386`` directory? If not, that'd probably solve the problem, although I think all Windows XP ISO's should have that directory.

**Comment by dsplice** [comment]
Seems the iso is corrupt.  Will retry with better image.
