### ISSUE TITLE
Download bad file?

### ISSUE THREAD

**Issue by futex** [jbremer/vmcloak#30]
When i install vmcloak, it dowload Silverlight_Developer_x86.exe and save it in Silverlight_Developer_x64.exe, and perfore the sha1 comparaison failed.

vmcloak -r --win7x64 Cuckoo --cuckoo /home/futex/Documents/Softs/Cuckoo/cuckoo --data-dir /home/futex/VirtualBox\ VMs --iso-mount /mnt/win7x64
--2015-06-15 13:30:08--  http://cuckoo.sh/vmcloak-files/Silverlight_Developer_x86.exe
Connexion à XXXXXXXX… connecté.
requête Proxy transmise, en attente de la réponse… 200 OK
Taille : 9331416 (8,9M) [application/octet-stream]
Sauvegarde en : « /home/futex/.vmcloak/deps/files/Silverlight_Developer_x64.exe »

/home/futex/.vmcloak/deps/files/Silverlight_Developer_x64.exe     100%[=====================================================================================================================================================================>]   8,90M  2,23MB/s   ds 3,5s   

2015-06-15 13:30:11 (2,53 MB/s) — « /home/futex/.vmcloak/deps/files/Silverlight_Developer_x64.exe » sauvegardé [9331416/9331416]

WARNING:vmcloak.deps:File Silverlight_Developer_x64.exe of dependency 'silverlight5' downloaded with an incorrect sha1.

**Comment by razuz** [comment]
I'll take a look at that and see what's up with that

**Comment by jbremer** [comment]
Thanks @futex @razuz!
