### ISSUE TITLE
install hangs on selection screen

### ISSUE THREAD

**Issue by lehuff** [jbremer/vmcloak#45]
Running the command to initialize the VM:

```vmcloak init --win7 testbox --netmask 255.255.255.0 --ip 10.10.10.71 --gateway 10.10.10.1```

Two lines of output are returned:

```
Warning: creating filesystem that does not conform to ISO-9660.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```

No progress after that happens.  When looking at the vm or using the ```--vm-visible``` command, the process seems to be hung during the Windows version selection screen.  Any hints on how to deal with this?  I can't find any documentation that says how to specify a windows version (other than x64).

**Comment by Svieg** [comment]
I ran into that too myself. Quickfix would be to start it with `--vm-visible` as you did and select the version you want but there is a click utility that may be useful for this. I dont know if it's doable and I have yet to try it. As for the problem of selecting a specific version, I don't think it's yet possible to do so apart from win7, win7x64 and WinXP. Jurriaan may have a solution for this though.

**Comment by lehuff** [comment]
I tried selecting the correct option with ```-vm-visible``` and nothing happened.  Even tried stepping through the install with no real luck.

**Comment by jbremer** [comment]
Which version of Windows are you installing @lehuff ?

**Comment by lehuff** [comment]
![screenshot from 2016-04-26 09-23-28](https://cloud.githubusercontent.com/assets/6956380/14819537/9ae0c838-0b90-11e6-9dab-9376145a372d.png)


I was aiming to install Professional x86 from the screenshot. Screenshot was grabbed using ```-vm-visibile```

**Comment by jbremer** [comment]
Yeah, sorry, at the moment only Windows 7 64-bit is supported (who uses 32-bit Windows 7 anyway?).
If somebody is interested to add support for 32-bit, though, that can be done by modifying the `vmcloak/data/win7/autounattend.xml` file, probably.

**Comment by lehuff** [comment]
32-bit VM's are useful for small vm within a vm analyses boxes. VBox doesn't support 64-bit nested virtualization. :\

**Comment by jbremer** [comment]
I feel an upcoming pull request! ;-)

**Comment by lehuff** [comment]
Pull request submitted!

**Comment by jbremer** [comment]
This has been resolved, thanks to @lehuff and @danieltdt.
