### ISSUE TITLE
agent.py should be minimized during install

### ISSUE THREAD

**Issue by razuz** [jbremer/vmcloak#61]
Currently when deploying with vmcloak the agent window will be open on desktop. This kind of creates issue that you have to use "vmcloak modify" to deploy the vm for cuckoo. well ... sometimes you're lazy and don't want to do that :)

**Comment by jbremer** [comment]
Thought I had already done this. This wasn't possible earlier due to some issues with the Cuckoo Analyzer, but this has been possible since a couple of months now - should enable.

**Comment by jbremer** [comment]
Please verify - needs a complete reinstall.

**Comment by razuz** [comment]
I'll do that and let you know

**Comment by KillerInstinct** [comment]
Why not just copy the file and set the destination to agent.pyw instead of agent.py? This would do the same thing.

https://github.com/jbremer/vmcloak/blob/1a5592067c15d4395e63e8ae9e6c99faf7c71cf7/vmcloak/data/bootstrap/bootstrap.bat#L25

**Comment by razuz** [comment]
@jbremer this patch works for me. Thanks !

**Comment by jbremer** [comment]
Thanks @razuz. This was the first thing that popped into mind, I guess that that method would have worked as well indeed.

**Comment by razuz** [comment]
lets close that I suppose :)
