### ISSUE TITLE
vmcloak install doesn't attach network on VirtualBox 5.1.2 and ubuntu 16.04

### ISSUE THREAD

**Issue by razuz** [jbremer/vmcloak#74]
adding this todo item for myself so I wouldn't forget :)

**Comment by razuz** [comment]
well that's really odd, but running on decent HW 5.1.2 needs more sleep before detaching disc. According to my tests I cannot go lower than 5 secs.

@jbremer maybe lets make disc and ISO detach sleep dynamic ? It's mainly useful also for older HW when  Virtualbox needs more time to release locks ...

**Comment by jbremer** [comment]
What about detaching the ISO and then polling `showvminfo` once a second until the ISO has been properly detached?

**Comment by razuz** [comment]
I'll test that option

**Comment by razuz** [comment]
so the main issue turned out to be new behaviour of virtualbox and is fixed by #77
