### ISSUE TITLE
Disable UAC

### ISSUE THREAD

**Issue by dasfreak** [jbremer/vmcloak#79]
Hey,

how about adding this line to the bootstrap.bat to disable User Account Control (UAC) on Windows 7+?

`C:\Windows\System32\cmd.exe /k %windir%\System32\reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f`

**Comment by jbremer** [comment]
Well, it's not necessarily required, so should we? :-)

**Comment by dasfreak** [comment]
You are right, it is not necessarily required.

But I was thinking about the case described here:
https://github.com/cuckoosandbox/cuckoo/issues/1028

where is32bit.exe fails if the user is not admin or UAC is enabled.

But anyone can disable UAC manually if he likes to :-)

**Comment by jbremer** [comment]
Yeah, but that error doesn't occur with VMs created through VMCloak ;-)
