### ISSUE TITLE
Sphinx conflict with cryptography version

### ISSUE THREAD

**Issue by Kolano** [jbremer/vmcloak#96]
Prior to running...
sudo python setup.py install
...I was able to run...
make singlehtml
...to generate documentation.

After running the VMCloak install trying to run Sphinx to generate documentation results in a version conflict error with cryptography...

```
sudo make singlehtml
sphinx-build -b singlehtml -d _build/doctrees   . _build/singlehtml
Running Sphinx v1.5a1

Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.3.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('cryptography>=1.3.4; extra == "security"'), set(['requests']))
The full traceback has been saved in /tmp/sphinx-err-GLcxYX.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [singlehtml] Error 1
```

**Comment by Kolano** [comment]
Updating cryptography...
sudo pip install --upgrade cryptography
...results in further errors related to setuptools...

```
sudo make singlehtml
sphinx-build -b singlehtml -d _build/doctrees   . _build/singlehtml
Running Sphinx v1.5a1

Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=11.3'), set(['cryptography']))
The full traceback has been saved in /tmp/sphinx-err-tF_8vP.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [singlehtml] Error 1
```

**Comment by jbremer** [comment]
I guess it'd be appropriate to update some of the dependencies, although some are shared with Cuckoo as well - where upgrading certain libraries (e.g., `sqlalchemy`) is quite some effort as we'll first be needing unit tests to ensure everything remains working after the upgrade. Simply put, it may be better for you to use `virtualenv` for your VMCloak & Cuckoo needs.
Hopefully that helps you - let me know if you have any additional questions and/or feedback.

**Comment by Kolano** [comment]
Thanks, I'll look into virtualenv's. Coming to terms with handling pythons dependencies across various projects.

It may be a moot point for the time being, since I think the documentation produced may be a bit out of date anyway. Not sure, but it doesn't seem they account for the usage changes from the .3 release yet, so not clear they are that helpful (It's a bit confusing actually).

**Comment by jbremer** [comment]
Hi @Kolano,
I've removed `sphinx` from the setup dependencies as it's an optional module and also replaced some obsolete documentation by URLs to the latest two blogposts (sees also #78).
No official release yet, but if you'd like to start using this new version, feel free to install `0.4.3a2`.
Closing this issue as resolved - please let me know if you have any other questions.
